import { firewallDemo } from "../lib/escrowFirewall.js";

function TermsColumn({ title, terms, emphasized = false }) {
  return (
    <section className={"terms-column" + (emphasized ? " terms-recalled" : "")}>
      <p className="eyebrow">{title}</p>
      <h3>{emphasized ? "Memory-informed terms" : "Generic terms"}</h3>
      <dl className="terms-list">
        <div>
          <dt>Acceptance criteria</dt>
          <dd>
            <ul>
              {terms.acceptance.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </dd>
        </div>
        <div>
          <dt>Required evidence</dt>
          <dd>
            <ul>
              {terms.evidence.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </dd>
        </div>
        <div>
          <dt>Milestone gate</dt>
          <dd>{terms.milestone}</dd>
        </div>
        <div>
          <dt>Review</dt>
          <dd>{terms.review}</dd>
        </div>
      </dl>
    </section>
  );
}

export default function EscrowFirewall() {
  const { taskCategory, generic, recalled } = firewallDemo;
  return (
    <div>
      <h2>Escrow Firewall — before funding</h2>
      <p className="lead">
        Same task category: <strong>{taskCategory}</strong>. The difference is not a provider
        score. A stored failure mechanism changes what the next provider must prove before
        escrow is funded.
      </p>

      <div className="card note firewall-context">
        <p className="eyebrow">Recalled Sibyl memory · demo fixture</p>
        <p>
          <code>pattern:{recalled.pattern}</code> · confidence {recalled.confidence}
        </p>
        <p className="lead">
          Countermeasure: require reproducible evidence before the milestone. This is a
          recommendation until the client approves it.
        </p>
      </div>

      <div className="terms-grid">
        <TermsColumn title="No recalled pattern" terms={generic} />
        <TermsColumn title="Relevant failure pattern recalled" terms={recalled} emphasized />
      </div>

      <div className="card firewall-commitment">
        <p className="eyebrow">Pre-funding commitment</p>
        <p>
          The approved canonical terms are hashed before <code>fund</code> and appended to ACP&apos;s
          immutable job description. Terms hash: <code>{recalled.commitment}</code>
        </p>
        <p className="lead">
          In a real run this value is generated by the agent CLI and included in the verdict
          evidence bundle. The value above is illustrative, so the page cannot be mistaken for
          a live transaction viewer.
        </p>
      </div>
    </div>
  );
}
